// UpdatePage.jsx — the "Update" / HMG tab: the weekly Hits / Misses / Goals summary
// for the manager (Nate), generated by the weekly-hmg-update skill in Claude Code
// and persisted to Second Brain/hmg/. Defaults to the CURRENT week (placeholder +
// prompt when it has no data yet); past weeks are browsable from the history strip.

import React from "react";
import { Icon } from "../components/shared.jsx";

const pad = (n) => String(n).padStart(2, "0");
const isoOf = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;

// Mon–Fri week containing `iso`; returns the Friday's ISO date + a human label
// matching the existing week labels (e.g. "June 1 – 5", "April 27 – May 1").
function currentWeek(iso) {
  const d = new Date(iso + "T00:00:00");
  const mon = new Date(d);
  mon.setDate(d.getDate() - ((d.getDay() + 6) % 7));
  const fri = new Date(mon);
  fri.setDate(mon.getDate() + 4);
  const mName = (x) => x.toLocaleDateString("en-US", { month: "long" });
  const label = mon.getMonth() === fri.getMonth()
    ? `${mName(mon)} ${mon.getDate()} – ${fri.getDate()}`
    : `${mName(mon)} ${mon.getDate()} – ${mName(fri)} ${fri.getDate()}`;
  return { friday: isoOf(fri), label };
}

function Section({ label, items, cls }) {
  return (
    <div className={"hmg-sec " + cls}>
      <div className="hmg-sec-h">{label}</div>
      {items.length ? (
        <ul className="hmg-list">{items.map((t, i) => <li key={i}>{t}</li>)}</ul>
      ) : (
        <div className="hmg-empty">(nothing recorded)</div>
      )}
    </div>
  );
}

export function UpdatePage({ hmg = [], today }) {
  const [sel, setSel] = React.useState(0);

  const todayISO = today || new Date().toISOString().slice(0, 10);
  const cw = currentWeek(todayISO);
  const hasCurrent = hmg.some((h) => h.friday === cw.friday);
  // Always lead with the current week. If the vault has no file for it yet, prepend
  // a placeholder so the tab still shows "this week" (with a prompt to populate it).
  const weeks = hasCurrent
    ? hmg
    : [{ id: "hmg-" + cw.friday, week: cw.label, friday: cw.friday, impact: "", hits: [], misses: [], goals: [], placeholder: true }, ...hmg];

  const cur = weeks[Math.min(sel, weeks.length - 1)];

  const history = weeks.length > 1 ? (
    <div className="hmg-history">
      <div className="page-label"><Icon name="clock" size={13} /> Weeks</div>
      <div className="hmg-weeks">
        {weeks.map((h, i) => (
          <button key={h.id} className={"hmg-week" + (i === sel ? " on" : "")} onClick={() => setSel(i)} type="button">
            {h.week || h.friday}{h.placeholder ? " (this week)" : ""}
          </button>
        ))}
      </div>
    </div>
  ) : null;

  return (
    <div className="page update-page">
      <div className="day-head">
        <div>
          <div className="page-sub" style={{ margin: 0 }}>Weekly update for Nate</div>
          <h1 className="page-title">{cur.week || cur.friday || "This week"}</h1>
          <div className="day-stat">
            {cur.hits.length} hits · {cur.misses.length} misses · {cur.goals.length} goals
            {cur.generated ? ` · generated ${cur.generated}` : ""}
          </div>
        </div>
      </div>

      {history}

      {cur.placeholder ? (
        <div className="page-empty">
          No update logged for this week yet. Run <code>/hmg-daily</code> (or <code>/hmg-to-vault</code>)
          in Claude Code to roll workspace work into it — it appears here live.
        </div>
      ) : (
        <>
          {cur.impact ? (
            <div className="hmg-impact"><Icon name="sparkle" size={16} stroke={2.2} /> {cur.impact}</div>
          ) : null}
          <Section label="Hits" items={cur.hits} cls="hits" />
          <Section label="Misses" items={cur.misses} cls="misses" />
          <Section label="Goals" items={cur.goals} cls="goals" />
        </>
      )}
    </div>
  );
}
